version: '3.8'

services:
  postgres:
    container_name: boom-postgres-dev
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=boom
      - POSTGRES_PASSWORD=boom_dev_password
      - POSTGRES_DB=boom_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - boom-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U boom"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: boom-backend-dev
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./nx.json:/app/nx.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      # Keep dist in sync for the built files
      - ./dist:/app/dist
      # Prevent overwriting node_modules and cache
      - /app/node_modules
      - /app/.nx
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=boom
      - DB_PASSWORD=boom_dev_password
      - DB_DATABASE=boom_dev
    networks:
      - boom-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    # Enable debug mode (optional)
    # ports:
    #   - "9229:9229"
    # command: ["npx", "nx", "serve", "backend", "--host", "0.0.0.0", "--inspect=0.0.0.0:9229"]

  frontend:
    container_name: boom-frontend-dev
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      # Mount source code for hot reload
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./nx.json:/app/nx.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      # Keep dist in sync for the built files
      - ./dist:/app/dist
      # Prevent overwriting node_modules and cache
      - /app/node_modules
      - /app/.nx
    environment:
      - NODE_ENV=development
    networks:
      - boom-network
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres-data:

networks:
  boom-network:
    driver: bridge
