version: '3.8'

services:
  backend:
    container_name: boom-backend-dev
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./nx.json:/app/nx.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      # Keep dist in sync for the built files
      - ./dist:/app/dist
      # Prevent overwriting node_modules and cache
      - /app/node_modules
      - /app/.nx
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
    networks:
      - boom-network
    restart: unless-stopped
    # Enable debug mode (optional)
    # ports:
    #   - "9229:9229"
    # command: ["npx", "nx", "serve", "backend", "--host", "0.0.0.0", "--inspect=0.0.0.0:9229"]

networks:
  boom-network:
    driver: bridge
