services:
  postgres:
    container_name: boom-postgres-dev
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - boom-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: boom-backend-dev
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      # Mount source code for hot reload
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./nx.json:/app/nx.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      # Keep dist in sync for the built files
      - ./dist:/app/dist
      # Prevent overwriting node_modules and cache
      - /app/node_modules
      - /app/.nx
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - HOST=${HOST}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - BOOM_API_BASE_URL=${BOOM_API_BASE_URL}
      - BOOM_CLIENT_ID=${BOOM_CLIENT_ID}
      - BOOM_CLIENT_SECRET=${BOOM_CLIENT_SECRET}
      - BOOM_OAUTH_URL=${BOOM_OAUTH_URL}
    networks:
      - boom-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    # Enable debug mode (optional)
    # ports:
    #   - "9229:9229"
    # command: ["npx", "nx", "serve", "backend", "--host", "0.0.0.0", "--inspect=0.0.0.0:9229"]

  frontend:
    container_name: boom-frontend-dev
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      # Mount source code for hot reload
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./nx.json:/app/nx.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      # Keep dist in sync for the built files
      - ./dist:/app/dist
      # Prevent overwriting node_modules and cache
      - /app/node_modules
      - /app/.nx
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - boom-network
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres-data:

networks:
  boom-network:
    driver: bridge
